-- H2 용 스키마 생성 및 설정
CREATE SCHEMA IF NOT EXISTS SHARED_CODE;
SET SCHEMA SHARED_CODE;

-- 통합 시퀀스(채번) 관리 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_SEQ_MANAGEMENT (
    SHARED_CODE_SEQ_MANAGEMENT_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    TABLE_NAME VARCHAR(50) NOT NULL,
    COLUMN_NAME VARCHAR(50) NOT NULL,
    SEQUENCE_NUMBER BIGINT NOT NULL,

    IS_USE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL,

    UNIQUE (TABLE_NAME, COLUMN_NAME, SEQUENCE_NUMBER)
    );

-- 통합 코드 관리 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_MANAGEMENT (
    SHARED_CODE_MANAGEMENT_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE_TYPE VARCHAR(20) NOT NULL,
    PARENT_CODE VARCHAR(10),
    CODE VARCHAR(10) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(255),
    SORT_ORDER INT,

    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL,

    UNIQUE (CODE_TYPE, CODE)
    );

-- 코드 상세 속성 관리 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_DETAIL_ATTRIBUTE_MANAGEMENT (
    SHARED_CODE_DETAIL_ATTRIBUTE_MANAGEMENT_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE_TYPE VARCHAR(20) NOT NULL,
    CODE VARCHAR(10) NOT NULL,

    ATTRIBUTE_CODE VARCHAR(10) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(20) NOT NULL,
    ATTRIBUTE_DESCRIPTION VARCHAR(255),
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,

    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL,

    UNIQUE (CODE_TYPE, CODE, ATTRIBUTE_CODE)
    );

-- 프로그램 관리 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_PROGRAM_MANAGEMENT (
    SHARED_CODE_PROGRAM_MANAGEMENT_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE_TYPE VARCHAR(20) NOT NULL,
    CODE VARCHAR(10) NOT NULL,

    PROGRAM_ID VARCHAR(10),
    PROGRAM_TYPE_CODE VARCHAR(10),
    PROGRAM_NAME VARCHAR(20) NOT NULL,
    PROGRAM_DESCRIPTION VARCHAR(255),
    PROGRAM_PATH VARCHAR(255),
    PROGRAM_PARAMETER VARCHAR(255),
    PROGRAM_USE_START_DATE TIMESTAMP,
    PROGRAM_USE_END_DATE TIMESTAMP,
    PROGRAM_SORT_ORDER INT,

    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL,

    UNIQUE (CODE_TYPE, CODE, PROGRAM_ID),
    UNIQUE (PROGRAM_PATH)
    );

-- H2 용 스키마 생성 및 설정
CREATE SCHEMA IF NOT EXISTS SHARED_CODE;
SET SCHEMA SHARED_CODE;

-- 메뉴관리 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_MENU_MANAGEMENT (
    SHARED_CODE_MENU_MANAGEMENT_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE_TYPE VARCHAR(20) NOT NULL,
    CODE VARCHAR(10) NOT NULL,

    UPPER_MENU_ID BIGINT,
    MENU_CODE VARCHAR(10),
    MENU_LEVEL INT DEFAULT 0,
    MENU_NAME VARCHAR(20) NOT NULL,
    MENU_SORT_ORDER INT,
    MENU_USE_START_DATE TIMESTAMP,
    MENU_USE_END_DATE TIMESTAMP,
    MENU_DESCRIPTION VARCHAR(255),
    MENU_TYPE_CODE VARCHAR(10),
    MENU_TYPE_NAME VARCHAR(20),
    MENU_TYPE_DESCRIPTION VARCHAR(255),
    MENU_PARAMETER VARCHAR(255),
    MULTI_OPEN_STATUS BOOLEAN,
    HELP_PAGE_LINK VARCHAR(255),

    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL,

    UNIQUE (CODE_TYPE, CODE, UPPER_MENU_ID, MENU_CODE)
    );

-- 권한 그룹 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_PERMISSION_GROUP (
    SHARED_CODE_PERMISSION_GROUP_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE_TYPE VARCHAR(20) NOT NULL,
    CODE VARCHAR(10) NOT NULL,

    PERMISSION_GROUP_ID VARCHAR(20) NOT NULL,
    PERMISSION_GROUP_NAME VARCHAR(20) NOT NULL,
    PERMISSION_GROUP_DESCRIPTION VARCHAR(255),
    PERMISSION_GROUP_START_DATE TIMESTAMP,
    PERMISSION_GROUP_END_DATE TIMESTAMP,

    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL,

    UNIQUE (CODE_TYPE, CODE, PERMISSION_GROUP_ID),
    UNIQUE (PERMISSION_GROUP_ID)
    );

-- 권한 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_PERMISSION (
    SHARED_CODE_PERMISSION_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,

    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL
    );

-- 권한 그룹과 권한의 관계 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_PERMISSION_GROUP_RELATION (
    SHARED_CODE_PERMISSION_GROUP_RELATION_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    PERMISSION_GROUP_SEQ BIGINT NOT NULL,
    PERMISSION_SEQ BIGINT NOT NULL,

    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL
    );

-- 권한 그룹과 사용자의 관계 테이블 생성
CREATE TABLE IF NOT EXISTS SHARED_CODE_PERMISSION_GROUP_USER_RELATION (
    SHARED_CODE_PERMISSION_GROUP_USER_RELATION_SEQ BIGINT PRIMARY KEY AUTO_INCREMENT,
    PERMISSION_GROUP_SEQ BIGINT NOT NULL,
    LOGIN_ID VARCHAR(20) NOT NULL,

    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER_ID VARCHAR(50),
    CREATE_USER_NAME VARCHAR(50),
    CREATE_IP VARCHAR(15),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATE_USER_ID VARCHAR(50),
    UPDATE_USER_NAME VARCHAR(50),
    UPDATE_IP VARCHAR(15),
    VERSION BIGINT DEFAULT 0 NOT NULL
    );

